name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rye
        uses: eifinger/setup-rye@v3
      - name: Install dependencies
        run: rye sync
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: rye run pytest
      - name: Lint
        run: rye run ruff check ./src
      - name: Format check
        run: rye run ruff format ./src

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    permissions:
      id-token: write
    environment:
      name: release
      url: https://pypi.org/p/qa-store
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rye
        uses: eifinger/setup-rye@v3
      - name: Install dependencies
        run: rye sync
      - name: Build package
        run: |
          rye run pip install build
          rye run python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
